@PORT=3001
@URL=http://localhost:{{PORT}}/api/
@TOKEN = {{Login.response.body.token}}
@USER_ID = {{Login.response.body.user.id}}

##### USERS
# @name CreateUser
POST {{URL}}user/create HTTP/1.1
content-type: application/json

{
    "name": "filipe", 
    "email": "filipema@gmail.com", 
    "password": "Test123@"
}

###
# @name CreateUserWithTwoFactory
POST {{URL}}user/create HTTP/1.1
content-type: application/json

{
    "name": "filipe marques", 
    "email": "filipema@gmail.com", 
    "password": "Test123@##",
    "two_factory": true
}

###
# @name GetUsers
GET {{URL}}users/
content-type: application/json

###
# @name DeleteUser
DELETE {{URL}}user/delete/
content-type: application/json

##### LOGIN
# @name Login
POST {{URL}}login HTTP/1.1
content-type: application/json

{
    "email": "filipema@gmail.com", 
    "password": "Test123@"
}

###
# @name LoginWithTwoFactory
POST {{URL}}login HTTP/1.1
content-type: application/json

{
    "email": "filipema@gmail.com", 
    "password": "Test123@##"
}

###
# @name LoginSecondStep
POST {{URL}}login/second-step HTTP/1.1
content-type: application/json

{
    "email": "filipema@gmail.com", 
    "hash": 570828
}

##### TODO
# @name GetAllTodos
GET {{URL}}todos/{{USER_ID}} HTTP/1.1
content-type: application/json
Authorization: {{TOKEN}}

###
# @name GetOneTodo
GET {{URL}}todos/{{USER_ID}}/id_todo HTTP/1.1
content-type: application/json
Authorization: {{TOKEN}}

###
# @name CreateTodo
POST {{URL}}todos/create/ HTTP/1.1
content-type: application/json
Authorization: {{TOKEN}}

{
    "task_title": "complete udemy course", 
    "task_description":"complete udemy course",
    "complete": true,
    "user_id": "{{USER_ID}}"
}

###
# @name ModifyTodo
PUT {{URL}}todos/modify/{{USER_ID}}/id_todo HTTP/1.1
content-type: application/json
Authorization: {{TOKEN}}

{
    "task": "complete udemy course", 
    "complete": false,
    "user_id": "{{USER_ID}}"
}

###
# @name DeleteTodo
DELETE  {{URL}}todos/delete/{{USER_ID}}/id_todo HTTP/1.1
content-type: application/json
Authorization: {{TOKEN}}